# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DouyinDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'lottie-ios'
  pod 'Kingfisher', '~> 6.3.1'
  pod 'SnapKit', '~> 5.0.0'

end
